### ISSUE TITLE
Cannot read property '$off' of undefined when ReactDOM.unmountComponentAtNode() is called

### ISSUE THREAD

**Issue by tomasz-krol** [froala/react-froala-wysiwyg#176]
##### Expected behavior.
react-froala-wysiwyg can be rendered and unmounted using [react-testing-library](https://github.com/testing-library/react-testing-library)
##### Actual behavior.
`TypeError: Cannot read property '$off' of undefined`

      at E.Bootstrap.destroy (node_modules/froala-editor/js/froala_editor.min.js:7:262255)
      at t.value (node_modules/react-froala-wysiwyg/index.js:1:4685)
      at t.value (node_modules/react-froala-wysiwyg/index.js:1:3086)
      at callComponentWillUnmountWithTimer (node_modules/react-dom/cjs/react-dom.development.js:17169:12)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:149:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:199:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)
      at safelyCallComponentWillUnmount (node_modules/react-dom/cjs/react-dom.development.js:17176:5)
      at commitUnmount (node_modules/react-dom/cjs/react-dom.development.js:17553:11)
      at unmountHostComponents (node_modules/react-dom/cjs/react-dom.development.js:17873:7)
      at commitDeletion (node_modules/react-dom/cjs/react-dom.development.js:17904:5)
      at commitAllHostEffects (node_modules/react-dom/cjs/react-dom.development.js:18685:11)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:149:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:199:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:18913:7)
      at node_modules/react-dom/cjs/react-dom.development.js:20418:5
      at Object.unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:20417:13)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:20346:9)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:20254:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:20228:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:20097:5)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:19911:5)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:20572:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:20600:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:20657:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:20953:3)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:21105:12)
      at node_modules/react-dom/cjs/react-dom.development.js:21178:9
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:20459:10)
      at Object.unmountComponentAtNode (node_modules/react-dom/cjs/react-dom.development.js:21177:7)
      at cleanupAtContainer (node_modules/@testing-library/react/dist/index.js:122:21)
          at Set.forEach (<anonymous>)
      at Object.cleanup (node_modules/@testing-library/react/dist/index.js:116:21)
`
##### Steps to reproduce the problem.
Repo highlighing the problem with react-testing-library: https://github.com/lukaszwnek/froala-react-testing-library
Repo highlighing the problem with ReactDOM: https://github.com/tomasz-krol/sample-react-froala-wysiwyg

1. clone the repo
2. run `yarn install`
3. run `yarn test`

##### react-froala-wysiwyg version
`3.0.2`

##### OS.
Any

### Related Issue
https://github.com/froala/wysiwyg-editor/issues/3504

**Comment by dcporter44** [comment]
happens to me when I refresh the page with an editor on it

**Comment by casualuser** [comment]
fixed in 3.0.4
