### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'isDisabled')

### ISSUE THREAD

**Issue by lmvet-ct** [froala/react-froala-wysiwyg#391]
I'm getting this error in my console and I'm not sure how to stop it. Is this something you are aware of? 

Any help with this would be great 

Thank you 

I'm using 
    "froala-editor": "^4.1.4",
    "react-froala-wysiwyg": "^4.1.4",
    
    
```
   import "froala-editor/css/froala_editor.pkgd.min.css";
import "froala-editor/js/plugins.pkgd.min.js";

import FroalaEditorComponent from "react-froala-wysiwyg";
import FroalaEditor from "froala-editor";
import {  useRef, useState } from "react";

const froalaEditorConfig: Partial<FroalaEditor> = {
  height: 400,
  quickInsertEnabled: false,
  imageDefaultWidth: 0,
  imageResizeWithPercent: true,
  imageMultipleStyles: false,
  imageOutputSize: true,
  imageRoundPercent: true,
  imageMaxSize: false,
  imagePaste: false,
  imageUpload: false,
  placeholderText: "",
};

const Froala =() => {
  const editorRef = useRef<FroalaEditorComponent>(null);
  const [model, setModel] = useState<string>("");

  const handleModelChange = (model: string) => {
    setModel(model);
  };
  return (
    <div id="editor">
      <FroalaEditorComponent
        ref={editorRef}
        model={model}
        onModelChange={handleModelChange}
        tag="div"
        config={froalaEditorConfig}
      ></FroalaEditorComponent>
    </div>
  );
};

export default Froala;
```
    

index-279f2ba2.js:387 Uncaught TypeError: Cannot read properties of undefined (reading 'isDisabled')
    at Pt (index-279f2ba2.js:387:15330)
    at HTMLDivElement.<anonymous> (index-279f2ba2.js:387:16761)
    at index-279f2ba2.js:512:30830
    at st (index-279f2ba2.js:382:5099)
Pt @ index-279f2ba2.js:387
(anonymous) @ index-279f2ba2.js:387
(anonymous) @ index-279f2ba2.js:512
st @ index-279f2ba2.js:382

![image](https://github.com/froala/react-froala-wysiwyg/assets/116560541/3c149e73-2c63-4bc5-882e-212f280ceda0)

**Comment by DhruvDhall** [comment]
I’m also facing the same issue. Is there any update or recommended workaround for this?
"react-froala-wysiwyg": "^4.5.0",
