### ISSUE TITLE
Webpack 3.5.5 issue when adding the fonts loaders

### ISSUE THREAD

**Issue by gazpachu** [froala/react-froala-wysiwyg#46]
```
yarn run v0.27.5
$ webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors
Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /Users/martosj/Dev/Webs/tapas-frontend
404s will fallback to /index.html
/Users/martosj/Dev/Webs/tapas-frontend/node_modules/loader-runner/lib/loadLoader.js:35
			throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
			^

Error: Module '/Users/martosj/Dev/Webs/tapas-frontend/node_modules/url/url.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/webpack/lib/NormalModule.js:181:3)
    at NormalModule.build (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/webpack/lib/NormalModule.js:274:15)
    at Compilation.buildModule (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/webpack/lib/Compilation.js:149:10)
    at factoryCallback (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/webpack/lib/Compilation.js:337:12)
    at factory (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/webpack/lib/NormalModuleFactory.js:241:5)
    at applyPluginsAsyncWaterfall (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
    at /Users/martosj/Dev/Webs/tapas-frontend/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/Users/martosj/Dev/Webs/tapas-frontend/node_modules/webpack/lib/NormalModuleFactory.js:194:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

And if I add

```
resolve: {
      modulesDirectories: ['node_modules']
    },
```

I get this error

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
error Command failed with exit code 1.
```

**Comment by gazpachu** [comment]
This solution fixes partially the issue: https://stackoverflow.com/questions/45674768/why-do-i-get-this-webpack-loader-error

The 2nd problem I have is that I'm using `svg-sprite-loader` to load the SVGs in my app, so I have conflict with the requirement for the SVGs of the editor.

Why there are so many dependencies? font-awesome, SVGs? ... I'm sure this could have been done with less external dependencies to make it easier to implement in projects :(

**Comment by lejager** [comment]
I'm running webpack 3.10.0. As mentioned above, when adding:
```
resolve: {
      modulesDirectories: ['node_modules']
    },
```
I get the following error:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
error Command failed with exit code 1.
```
Without adding the resolve, the css compiles correctly but tries to find the fonts relative to the current page. Any insight would be most appreciated.
